Update XF Android Project #31
PrismLibrary/Prism.Templates pull request #32
Opened 2021-03-13 03:20 UTC by Pietervdw

I've cleanup up the Android project by removing the layout/Tabbar  and layout/Toolbar xml files and removing references to them in the MainActivity OnCreate method.

I moved the color declarations to the colors.xml file and updated the styles.xml file to reference the default colors from there. The launcher_background color is already referenced from there, so thought it would make sense to centralize the colors. Let me know if this is ok.

2021-03-13 03:20 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/PrismLibrary/Prism.Templates?pullRequest=32) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/PrismLibrary/Prism.Templates?pullRequest=32) before we can accept your contribution.<br/><br/>:x: Pietervdw [sign now](https://cla.dotnetfoundation.org/PrismLibrary/Prism.Templates?pullRequest=32)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/PrismLibrary/Prism.Templates?pullRequest=32) it.</sub>

2021-03-22 18:26 UTC, dansiegel requested changes

2021-03-22 18:26 UTC, dansiegel commented on Xamarin.Forms/BlankApp/BlankApp.Android/Resources/values/colors.xml
> +    <color name="colorAccent">#FF4081</color>
this shouldn't be changed... we specifically use colors for Prism :)

2021-03-22 18:26 UTC, dansiegel commented on Xamarin.Forms/BlankApp/BlankApp.Android/BlankApp.Android.csproj
> +    <!--/-:cnd:noEmit -->
please revert these changes

2021-03-23 05:29 UTC, Pietervdw commented on Xamarin.Forms/BlankApp/BlankApp.Android/BlankApp.Android.csproj
> +    <!--/-:cnd:noEmit -->
Should the Tabbar.xml and Toolbar.xml not be removed?

2021-03-23 05:38 UTC, Pietervdw commented on Xamarin.Forms/BlankApp/BlankApp.Android/Resources/values/colors.xml
> +    <color name="colorAccent">#FF4081</color>
Moved the colors back to styles.xml

2021-03-23 14:26 UTC, dansiegel requested changes

2021-03-23 14:26 UTC, dansiegel commented on Xamarin.Forms/BlankApp/BlankApp.Android/Resources/values/styles.xml
> +    <!-- colorAccent is used as the default value for colorControlActivated which is used to tint widgets -->
not sure why you reverted this as well... the changes here to properly reference the colors were good... we just wanted the colors themselves preserved

2021-03-23 14:26 UTC, dansiegel commented on Xamarin.Forms/BlankApp/BlankApp.Android/BlankApp.Android.csproj
> +    <!--/-:cnd:noEmit -->
I just want the noEmit condition lines reverted... there's no reason to change these

2021-03-23 15:20 UTC, Pietervdw commented on Xamarin.Forms/BlankApp/BlankApp.Android/BlankApp.Android.csproj
> +    <!--/-:cnd:noEmit -->
Oh! Sorry Dan. I had a moment. Couldn't understand at first because I didn't add the lines. You're referring to the indentation. Doh! :) Sorry!

2021-03-24 05:48 UTC, Pietervdw commented on Xamarin.Forms/BlankApp/BlankApp.Android/Resources/values/styles.xml
> +    <!-- colorAccent is used as the default value for colorControlActivated which is used to tint widgets -->
Apologies for the misunderstanding. I've changed styles.xml to use the colors specified in colors.xml.

2021-03-24 05:54 UTC, Pietervdw commented on Xamarin.Forms/BlankApp/BlankApp.Android/Resources/values/styles.xml
> +    <!-- colorAccent is used as the default value for colorControlActivated which is used to tint widgets -->
The status and action bars will  now be the greyish colors instead of the usual blue. 

![image](https://user-images.githubusercontent.com/5253872/112262296-1e75d380-8c76-11eb-8521-b51cdda7c704.png)

2021-03-24 05:59 UTC, dansiegel approved these changes

2021-03-24 05:59 UTC, merged